#!/bin/sh
# Resolve the three allowlisted hosts into the pf table, so the Supabase host
# is never written by hand in two places.
set -eu
REPO=$(cd "$(dirname "$0")/.." && pwd)
HOST=$(sed -n 's/^supabase_host *= *"\(.*\)"/\1/p' "$REPO/config/desk.toml")
HOSTS="api.anthropic.com github.com"
[ -n "$HOST" ] && HOSTS="$HOSTS $HOST"

echo "# generated by scripts/egress_table.sh — do not edit by hand"
for h in $HOSTS; do
  dig +short "$h" A 2>/dev/null | grep -E '^[0-9.]+$' | sed "s|^|# $h |"
done
printf 'table <desk_egress> persist { '
for h in $HOSTS; do dig +short "$h" A 2>/dev/null | grep -E '^[0-9.]+$' | tr '\n' ' '; done
printf '}\n'
echo
echo "# NOTE: these hosts are behind CDNs and their addresses rotate." >&2
echo "# Re-run this on a schedule, or prefer Little Snitch, which filters by" >&2
echo "# hostname rather than address. See docs/EGRESS.md." >&2
